name: Publish on Netlify
on:
jobs:
  push:
    publish:
      runs-on: ubuntu-latest
      steps:   
      - uses: actions/checkout@master
      - run: sudo apt update && sudo apt install asciidoctor && sudo apt install linkchecker
      - run: make all
      - run: linkchecker --check-extern ./dist/main.html
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=./dist/
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  
  pull_request:
    publish:
        runs-on: ubuntu-latest
        steps:   
        - uses: actions/checkout@master
        - run: sudo apt update && sudo apt install asciidoctor && sudo apt install linkchecker
        - run: make all
        - run: linkchecker --check-extern ./dist/main.html